### ISSUE TITLE
Propose to delete / sunset Bokeh.jl repo

### ISSUE THREAD

**Issue by bryevdv** [samuelcolvin/Bokeh.jl#38]
There has been no work on Bokeh.jl in several years, and it has was last updated for Bokeh 0.4 which is ancient at this point. Although I think that Bokeh and Julia would make a terrific combination, there has also been no interest from the community in picking up maintenance of Bokeh.jl, despite a few different attempts to reach out. 

Given that, rather than indefinitely host a hopelessly outdated project, I propose to delete this repo entirely, sometime before a Bokeh 1.0 release. Alternatively, I would also be amenable to moving this repo out of the Bokeh organization into another GH org or user account. 

@bokeh/bokeh-julia 
@bokeh/dev

**Comment by samuelcolvin** [comment]
Why don't we move it back to me? I'll put a prominent message saying "discontinued see <this> issue".

Sad end to a bright idea, but I haven't worked on Julia at all in several years. I entirely agree with you about not keeping obsolete projects hanging around.

**Comment by bryevdv** [comment]
@samuelcolvin I am happy to do that, let me look into what is required.

**Comment by bryevdv** [comment]
@samuelcolvin it looks like there is a big red "transfer ownership" button.  I've also gotten no objection from @pzwang so as soon as you give me a final go-ahead I will make the transfer.

**Comment by samuelcolvin** [comment]
go ahead.

**Comment by bryevdv** [comment]
@samuelcolvin I get this message:
```
samuelcolvin/Bokeh.jl already exists and You can only transfer a repository from an organization to yourself at this time
```
It seems the options are:

* just delete this repo, if your copy is up to date / sufficient

* delete your version, and you would have to do the transfer (I think)

**Comment by samuelcolvin** [comment]
Done.

I deleted mine and did the transfer.

**Comment by bryevdv** [comment]
@samuelcolvin great, thanks! And thanks for lighting the way early on that it's possible to make other language bindings for Bokeh. I do hope some day Bokeh+Julia might get revisited.

**Comment by samuelcolvin** [comment]
No problem. Thanks for Bokeh.
